name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    connect-timeout = 5
    stalled-download-timeout = 30
    download-attempts = 3

jobs:
  go-test:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'src/failover/go.mod'
        cache-dependency-path: 'src/failover/go.sum'
    - name: Run Go tests
      working-directory: src/failover
      run: go test -v -cover ./...

  setup:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v21
      with:
        extra-conf: ${{ env.NIX_CONFIG }}
    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v13
          
    - name: Generate Matrix
      id: set-matrix
      run: |
        CHECKS=$(nix eval --json .#checks.x86_64-linux --apply builtins.attrNames)
        echo "matrix=$CHECKS" >> "$GITHUB_OUTPUT"

  check:
    needs: setup
    name: Check ${{ matrix.check }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        check: ${{ fromJson(needs.setup.outputs.matrix) }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v21
      with:
        extra-conf: ${{ env.NIX_CONFIG }}
    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v13
          
    - name: Run check
      run: nix build -L .#checks.x86_64-linux.${{ matrix.check }}
